[package]
name = "cache_metrics"
version = "0.1.0"
authors = ["Erik Johnston <erik@jki.re>"]
edition = "2018"

[dependencies]
bloom = "0.3.2"
cuckoofilter = "0.3.2"
probabilistic-collections = "0.7.0"
